# Generated by Django 3.0.7 on 2020-06-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechAndTools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tech_and_tools',
            field=models.ManyToManyField(related_name='techandtools', to='portfolio.TechAndTools'),
        ),
    ]
