# Generated by Django 3.0.7 on 2020-06-13 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('portfolio', '0002_auto_20200613_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('contact_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(help_text='425x425px recommmended', upload_to='profile_pics')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('linkedin_url', models.CharField(max_length=100)),
                ('github_url', models.CharField(max_length=50)),
                ('about_me', models.CharField(max_length=500)),
                ('cv_link', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='tech_and_tools',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.AddField(
            model_name='project',
            name='demo_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='repo_link',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='techandtools',
            name='project',
            field=models.ManyToManyField(related_name='techandtools', to='portfolio.Project'),
        ),
    ]
