# Generated by Django 3.0.7 on 2020-06-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200613_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techandtools',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='tech_and_tools',
            field=models.ManyToManyField(related_name='techandtools', to='portfolio.TechAndTools'),
        ),
    ]
