# Generated by Django 3.0.7 on 2020-06-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200613_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_and_tools',
        ),
        migrations.AddField(
            model_name='techandtools',
            name='project',
            field=models.ManyToManyField(related_name='techandtools', to='portfolio.Project'),
        ),
    ]
