# Generated by Django 3.0.7 on 2020-06-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200613_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='publication_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='repo_link',
            field=models.URLField(blank=True),
        ),
    ]
