# Generated by Django 3.0.7 on 2020-06-19 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200614_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(help_text='452x588px recommmended', upload_to='portfolio/profile_pics'),
        ),
    ]
