# Generated by Django 3.0.7 on 2020-06-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_auto_20200619_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=0.0006965174129353233, max_length=200),
            preserve_default=False,
        ),
    ]
