# Generated by Django 3.0.7 on 2020-06-19 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_profile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cv_link',
            field=models.FileField(upload_to='portfolio'),
        ),
    ]
