# Generated by Django 3.0.7 on 2020-06-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20200619_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='external_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cv_link',
            field=models.FileField(upload_to='portfolio/resume/'),
        ),
    ]
