# Generated by Django 3.0.7 on 2020-06-21 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20200619_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cv_link_external',
            field=models.CharField(default='https://docs.google.com/document/d/1_E71darfvZ--6YrtnCfKTYVjuuOqInXQNOlMBBxYnEw/edit?usp=sharing', max_length=100),
            preserve_default=False,
        ),
    ]
