# Generated by Django 3.0.7 on 2020-06-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20200620_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_comments',
            field=models.BooleanField(default=False),
        ),
    ]
